name: Run Days

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run start 1
      - run: npm run start 2
      - run: npm run start 3
      - run: npm run start 4
      - run: npm run start 5
      - run: npm run start 6
      - run: npm run start 7
      - run: npm run start 8
      - run: npm run start 9
      - run: npm run start 10
      - run: npm run start 11
